language: go

go:
    - "1.9" 
    - "1.10"

script:
    - go test -v $(go list ./... | grep -v /vendor/)
    
# whitelist
branches:
    only:
        - master

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
