language: go
      
go:
  - "1.10"

# This will run on Travis' 'new' container-based infrastructure
sudo: false

cache:
  apt: true

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - go test -v $(go list ./... | grep -v /vendor/)

jobs:
  include:
    - stage: deploy
      script: skip
      if: tag =~ ^v\d+
      deploy:
        provider: script
        skip_cleanup: true
        script: curl -sL http://git.io/goreleaser | bash
        on:
          tags: true
          condition: $TRAVIS_OS_NAME = linux

    - stage: doxygen 
      script: cd cpp/docs && doxygen && cd $TRAVIS_BUILD_DIR
      deploy:
        provider: pages
        project-name: libfileseq
        local-dir: cpp/docs/build
        skip_cleanup: true
        keep-history: true
        github-token: $GH_REPO_TOKEN
        on:
          branch: master
